"""Pydantic schema describing the full video plan generated by Gemini."""

from pydantic import BaseModel, Field

# Voices available for Gemini TTS (prebuilt voice names).
TTS_VOICES = [
    "Zephyr", "Puck", "Charon", "Kore", "Fenrir", "Leda", "Orus", "Aoede",
    "Callirrhoe", "Autonoe", "Enceladus", "Iapetus", "Umbriel", "Algieba",
    "Despina", "Erinome", "Algenib", "Rasalgethi", "Laomedeia", "Achernar",
    "Alnilam", "Schedar", "Gacrux", "Pulcherrima", "Achird", "Zubenelgenubi",
    "Vindemiatrix", "Sadachbia", "Sadaltager", "Sulafat",
]


class Character(BaseModel):
    name: str = Field(description="キャラクターの名前")
    personality: str = Field(description="性格・役割の説明")
    appearance_prompt: str = Field(
        description="Imagen向けの英語の見た目プロンプト(服装・体格・髪型・画風などを具体的に)"
    )
    voice_name: str = Field(
        description=f"Gemini TTS用の声質名。次のいずれかを選ぶ: {', '.join(TTS_VOICES)}"
    )
    voice_style: str = Field(
        description="話し方・トーン・速度などの指示(日本語または英語)"
    )


class DialogueLine(BaseModel):
    character: str = Field(description="発話するキャラクターの名前(Charactersのnameと一致)")
    text: str = Field(description="セリフ・ナレーション本文")


class Scene(BaseModel):
    index: int = Field(description="シーン番号(1から)")
    title: str = Field(description="シーンの短い見出し")
    description: str = Field(description="シーンの内容(日本語の説明)")
    veo_prompt: str = Field(
        description="Veo向けの英語の動画生成プロンプト。カメラワーク・画風・動き・雰囲気を具体的に記述"
    )
    duration_seconds: int = Field(
        description="このシーンの長さ(秒)。5または8を推奨"
    )
    dialogue: list[DialogueLine] = Field(
        default_factory=list, description="このシーンのセリフ/ナレーション一覧(順番に再生)"
    )


class VisualStyle(BaseModel):
    base_prompt: str = Field(
        description=(
            "全シーン共通のVeo向け英語スタイル指定。アートスタイル・色調・ライティング・画風・"
            "カメラレンズ感などを具体的に記述。例: "
            "'2D anime style, Studio Ghibli inspired, warm muted color palette, "
            "soft natural lighting, hand-drawn look, consistent character design throughout'"
        )
    )
    description: str = Field(description="スタイルの説明(日本語)")


class Music(BaseModel):
    bgm_prompt: str = Field(
        description="Lyria向けの英語の音楽生成プロンプト。ジャンル・楽器・テンポ・雰囲気を具体的に"
    )
    mood: str = Field(description="楽曲の雰囲気の説明(日本語)")


class VideoPlan(BaseModel):
    title: str = Field(description="動画のタイトル")
    synopsis: str = Field(description="全体のあらすじ・コンセプト(日本語)")
    visual_style: VisualStyle = Field(description="全シーン共通のビジュアルスタイル")
    characters: list[Character] = Field(description="登場キャラクター一覧")
    music: Music = Field(description="動画全体のBGM設定")
    scenes: list[Scene] = Field(description="シーンのリスト(再生順)")
